version: '3.5'

services:
  php:
    build:
      context: .
      dockerfile: docker/runner/php/Dockerfile
    volumes:
      - web:/var/www/html
      - auth:/var/www/auth
    networks:
      default:
        ipv4_address: 10.5.0.2

  nginx-web:
    image: nginx:1.17.5
    ports:
      - 8080:80
    volumes:
      - web:/var/www/html
      - ./docker/runner/nginx/web.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      default:
        ipv4_address: 10.5.0.3
    expose:
      - 80

  nginx-auth:
    image: nginx:1.17.5
    ports:
      - 8081:80
    volumes:
      - auth:/var/www/auth
      - ./docker/runner/nginx/auth.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      default:
        ipv4_address: 10.5.0.4
    expose:
      - 80

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: datamanagement
      MYSQL_PASSWORD: datamanagement
      MYSQL_DATABASE: datamanagement
    networks:
      default:
        ipv4_address: 10.5.0.5
    expose:
      - 3306

  node:
    build:
      context: .
      dockerfile: docker/runner/node/Dockerfile
    volumes:
      - frontend:/var/www
    ports:
      - 4200:4200
    networks:
      default:
        ipv4_address: 10.5.0.6
    expose:
      - 4200

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16

volumes:
  web:
    driver: local
    driver_opts:
      type: none
      device: $PWD/backend
      o: bind

  auth:
    driver: local
    driver_opts:
      type: none
      device: $PWD/auth
      o: bind

  frontend:
    driver: local
    driver_opts:
      type: none
      device: $PWD/frontend
      o: bind

  db:
    driver: local
    driver_opts:
      type: none
      device: $PWD/docker/runner/data/mysql
      o: bind
